"""
MadLibs
Author: Luke H
Period/Core: C


"""
name = input("Enter name: ")
adjective = input("Enter adjective: ")
hum = input("Enter a hum (ex: bum du bum du dum: ")
character = input("Enter another name: ")
action = input("enter an action(no s at the end and related to adjective): ")
character2 = input("Enter another name: ")
character3 = input("Enter another name: ")
vehicle = input("Enter vehicle: ")
friend = input("enter synonym of friend: ")
character4 = input("Enter another name: ")

print(name + ": " + hum + ", It is good day not to be" + " " + adjective + "!")
print(character + " " + action + "s "  + name)
print(character + ": Pow! you are" + " " + adjective + "!")
print(name + ": I am "+adjective + "!")
print(character2 + ": " + hum)
print(character2 + ": Oh! " + name + " "  + "is " + adjective + "!")
print(name + ": I am "+adjective + "!")
print(character2 + ": why is " + name + " " + adjective + "?")
print(character + ": I don't know!")
print(name + ": I think it was-")
print(f"{character} and {character2} : shh, you are {adjective}!")
print(name + ": Ok.")
print(character3 + ": Gets out of " + vehicle + "*, What's up " + friend + "s- What just happened?!")
print(character + " and " + character2 + ": " + name + " " + "is " + adjective + "!")
print(character3 + ": " + name + " " + "is dead?!")
print(character2 + ": Correct!")
print(character2 + ": So, did you see the " + action + "er?")
print("Everyone: No, sorry.")
print(character2 + ": I will find him, I will capture him, and no one  will ever " + action + " again!")
print("Everyone: Appluads")
print(character3 + ": Ah, well that's nice.")
print(character + ": I am so proud right now!")
print(character4 + ": Attention!!!")
print(character4 + ": " + name + " is " + adjective + "!")
print(character2 + ": We know!")
print(character4 + ": Who " + action + "ed him?")
print(character2 + ": We don't know!")
print(character4 + ": I will find clues!")
print(character4 + ": What's that? An object? That thing is why " + name + " is " + adjective + "!")
print("Everyone: " + name + " is " + adjective + "!?!" )
print("END")